# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":hh"
    replace: "👋👋🏼👋🏿"

  - trigger: ":gi"
    replace: '¯\_(ツ)_/¯'

  - trigger: ":mail"
    replace: "koetjeboeh@gmail.com"

  - trigger: ":mvg"
    replace: "Met vriendelijke groet,\nFabio Bruna"

  - trigger: ":commit"
    form: 'git commit -m "{{message}}"'

#Zettlekasten

# Weeklog (CONCEPT)
  - trigger: ":nwn"
    replace: "# {{date}} weeklog\n\n ![[{{date}}]]\n\n ![[{{m1}}]]\n\n![[{{m2}}]]\n\n![[{{m3}}]]\n\n![[{{m4}}]]\n\n![[{{m5}}]]\n\n![[{{m6}}]]\n\n## Highs \n\n## Lows"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
      - name: m1
        type: shell
        params:
          cmd: "date -v-1d +%Y-%m-%d"
          # linux: cmd: 'date -d"-1 day" "+%Y-%m-%d"'
- name: m2
        type: shell
        params:
          cmd: "date -v-2d +%Y-%m-%d"
      - name: m3
        type: shell
        params:
          cmd: "date -v-3d +%Y-%m-%d"
      - name: m4
        type: shell
        params:
          cmd: "date -v-4d +%Y-%m-%d"
      - name: m5
        type: shell
        params:
          cmd: "date -v-5d +%Y-%m-%d"
      - name: m6
        type: shell
        params:
          cmd: "date -v-6d +%Y-%m-%d"

# Maandlog (CONCEPT)
  - trigger: ":nmn"
    replace: "# Maandlog {{date}}\n\n## Terugkijken \n\n## Meenemen\n"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  # Dates
  - trigger: ":dt"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":ti"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M"

# onderstaande twee commando's samenvoegen?

  - trigger: ":obsn"
    replace: "[[{{vorige}}|<< Vorige]] [[{{volgende}}|Volgende>>]]"
    vars:
      - name: volgende
        type: shell
        params:
          cmd: "date -v+1d +%Y-%m-%d"
          # linux: cmd: 'date -d"+1 day" "+%Y-%m-%d"'
      - name: vorige
        type: shell
        params:
          cmd: "date -v-1d +%Y-%m-%d"
          # linux: cmd: 'date -d"-1 day" "+%Y-%m-%d"'

# fun

  - trigger: ":wfh"
    replace: "🏠 ωοяκιηg ƒяοм нοмε"
